### ISSUE TITLE
Missing Data if More than 5 GPUS

### ISSUE THREAD

**Issue by codesport** [ethash/eminer-release#1]
**TL;DR: Complete stats only appear for the first five GPUs.**

If there are more than 5 GPUs, the mclock, temperature, and fanspeed for those extra GPUs are not being reported and only show as 0.  This issue exists in the CLI terminal as well as on the local web server on port 8550.

**Comment by ethash** [comment]
Thanks for your report, What is the OS?

**Comment by codesport** [comment]
We're running on a linux box with 16.04.3 LTS

**Comment by ethash** [comment]
I tested only 5 devices, could you please send output of ls -l /sys/bus/pci/devices/

Probably the problem is pci bus ids. I can solve the problem with this output.

**Comment by codesport** [comment]
![pcie-addresses](https://user-images.githubusercontent.com/5884033/30189967-251e56c0-9405-11e7-9fb7-736bb71b9f43.png)

**Comment by ethash** [comment]
Thanks, I see, I will fix in this next release.

**Comment by codesport** [comment]
Help me understand the output.  What would the PCIE bus ID of GPU 2 and GPU 8 (using 0-indexed id numbers)?

**Comment by codesport** [comment]
This is for a rig with 9 PCI-E slots:

![9-pcie-addresses](https://user-images.githubusercontent.com/5884033/30244382-d1c12c00-958a-11e7-86d8-cf62216351fe.png)
:

**Comment by ethash** [comment]
I fixed the problem in next release thanks your support.

**Comment by codesport** [comment]
Thanks for your responsiveness. Keep up the great work on this!
