### ISSUE TITLE
Any setup information to link into awesome miner ?

### ISSUE THREAD

**Issue by Horsetoothless** [ethash/eminer-release#10]
Got eminer to startup through awesome miner but interface is offline for reporting activity there,
 thought it was sending out global information string that would be picked up by awesome.
Anything that I need to add to my start file?

setx GPU_FORCE_64BIT_PTR 0
setx GPU_MAX_HEAP_SIZE 100
setx GPU_USE_SYNC_OBJECTS 1
setx GPU_MAX_ALLOC_PERCENT 100
setx GPU_SINGLE_ALLOC_PERCENT 100
eminer.exe -S stratum+tcp://europe.ethash-hub.miningpoolhub.com:20535  -U Horsetoothless.rig1 -P x -N rig1 --cloud-key 8da21f8e8671e8e462b03821be4a8fd9248c1d91

**Comment by Horsetoothless** [comment]
"API Listen" NEEDS TO BE ENABLED FROM "TEST CONNECTION." ERROR MESSAGE  in miner properties
of "Awesome miner" hope find my % nitch in this wild world of the crypto chaos  hope get your miner added there  project started, my Avg antivirus keeps killing other miners upon download there.
what is your % ? 1% from what I have seen? could be lowered and make some market value 
from that place I Believe.

**Comment by ethash** [comment]
I sent mail to awesome miner but they don't answer my mails. Can you send the request to them? Firstly they should implement eminer.

**Comment by Horsetoothless** [comment]
I emailed them last night, no info from any mining activity shows up there on awesome,
is the API listen set enabled in eminer, test says it in error there.

**Comment by Horsetoothless** [comment]
no data on awesome issue needs reopened or will start new one
is the API listen set enabled for them to get it?
 copy of email sent for getting adopted there.
From: Brian Donnelly <bdonnelly80526@gmail.com>
Date: Sat, Sep 23, 2017 at 4:50 PM
Subject: New Miner Program to look at for addition there.
To: info@awesomeminer.com


https://github.com/ethash/eminer-release

Did get this one to start running there on your free version but see issues
on github for more.

Am just crawling back into the Crypto world and like your program so far.

Except the antivirus / miner issues out there.
looking to find my nitch market share here,
as I start my mining.
