### ISSUE TITLE
No Data  Found for Cloudkey @ usa.nicehash.com:3353

### ISSUE THREAD

**Issue by Horsetoothless** [ethash/eminer-release#13]
Ran overnight still looking for data for the Cloudkey there.

"No data found for this key" returned.

will be looking at other pools too.

**Comment by Horsetoothless** [comment]
eu.nicehash.com:3353 also no data found for key

**Comment by ethash** [comment]
You can use the key for statistics for https://cloud.eminer.net . You can create a free key from the web site. The key is not for other statistics service.

**Comment by Horsetoothless** [comment]
-S stratum+tcp://daggerhashimoto.eu.nicehash.com:3353  -U 3ERZzWyFG9rV4ofWe871LD6Hd8ND3Ndvs3.rig3 -P x -N rig3 --cloud-key 8da21f8e8671e8e462b03821be4a8fd9248c1d91

ON HERE NOW NO DATA FOR KEY FOUND THERE
