### ISSUE TITLE
Feature Request: Failover by Port 

### ISSUE THREAD

**Issue by codesport** [ethash/eminer-release#2]
I noticed that Eminer was attempting to connect to us1.ethermine.org for at least 30 minutes without success.

Would you add the ability to either manually specify or auto-detect available fail-overs and then switch-over if connection fails to main pooling server or port?

For example, for the East Coast (USA) Ethermine pool they offer 2 port options:

**Main Port:** us1.ethermine.org:4444 
**Secondary Port:** us1.ethermine.org:14444

It would be great if your E-miner can switch to the secondary port after multiple failures or not being able to connect to main port within 10 seconds or so.  

Thanks

**Comment by ethash** [comment]
You can use multi stratum servers for failover like this;

"-S us1.ethermine.org:4444,us1.ethermine.org:14444" , miner will be try another server while connection problems.

**Comment by codesport** [comment]
Thanks for clarifying.
